### ISSUE TITLE
Inconsistencies in Example Code Execution

### ISSUE THREAD

**Issue by yxwang8775** [nlp-uoregon/ullme#1]
Thank you for providing this repository. However, I've encountered some issues while trying to run the example code.

It seems that certain variables or module paths are inconsistent, which prevents the code from executing correctly. For instance:
In ullme/models/bidirectional_modelings/modeling_bidirectional_llama.py, line 29 references src.models, but src does not seem to exist.
Additionally, the README mentions running python -m genc.main, but genc.main is also missing.

Could you please provide a working example of the training pipeline? This would greatly help in understanding and utilizing the code. Thank you for your assistance!

**Comment by hieum98** [comment]
I appreciate your interest in our work. We updated the codebase to be compatible with HF 4.6!
